name: xhr_interceptor_facade
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Kulshekhar Kabra <kulshekhar+dart@gmail.com>
homepage: https://github.com/kulshekhar/xhr-interceptor-facade

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  js: '^0.6.1'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
